import type { Metadata } from "next";
import Link from "next/link";
import MarkdownToPdfTool from "@/components/MarkdownToPdfTool";
import Faq from "@/components/Faq";
import JsonLd from "@/components/JsonLd";
import BlogCluster from "@/components/BlogCluster";
import { getPostsByTopic } from "@/lib/blog";
import { SITE } from "@/lib/site";

// Measured 2026-09-17 via the GSC URL Inspection API: this page was still
// "Discovered - currently not indexed" and had never been crawled, three months
// after launch — while carrying only 672 words, the thinnest page on the site,
// and zero editorial inbound links (header, footer and the blog aside link here
// on every page, but no in-content link ever did). Both were fixed together:
// the page was rebuilt below, and four contextual links were added from
// convert-markdown-to-pdf, markdown-resume-to-pdf, convert-github-readme-to-pdf
// and markdown-cheat-sheet.
export const metadata: Metadata = {
  title: "Markdown to PDF Converter — Free Online Tool",
  description:
    "Convert Markdown to PDF online free. MD to PDF with headings, tables and code blocks, real selectable text, no watermark — runs entirely in your browser.",
  alternates: { canonical: "/markdown-to-pdf" },
  openGraph: {
    title: "Markdown to PDF Converter — Free Online Tool",
    description:
      "Convert Markdown to PDF online for free. Real selectable text, no watermark, 100% private.",
    url: "/markdown-to-pdf",
  },
};

const faqItems = [
  {
    question: "How do I convert Markdown to PDF?",
    answer:
      "Paste or type your Markdown in the editor above, or open an existing .md file. Check the live preview, then click Download PDF — the document is generated instantly in your browser.",
  },
  {
    question: "What Markdown features are supported?",
    answer:
      "Headings (H1–H6), paragraphs, bold and italic text, ordered and unordered lists (including nesting), links, inline code, fenced code blocks, blockquotes, tables, and horizontal rules.",
  },
  {
    question: "Is the PDF real text or an image?",
    answer:
      "Real text. The PDF is generated as vector text, so it is selectable, searchable, accessible to screen readers, and small in file size — unlike converters that screenshot the page.",
  },
  {
    question: "Does the converter add a watermark?",
    answer: "No. The generated PDF is completely clean, with no watermark or branding.",
  },
  {
    question: "Can I use it for GitHub README files?",
    answer:
      "Yes. Open your README.md in the editor and download it as a PDF — useful for sharing documentation with people outside your repository.",
  },
  {
    question: "How do I convert an .md file to PDF?",
    answer:
      "Open the file on your computer, copy its contents into the editor above (or use the file picker), check the preview, and click Download PDF. There is nothing to install and no account to create — MD to PDF conversion happens entirely in this page.",
  },
  {
    question: "Are my files uploaded to a server?",
    answer:
      "No. The Markdown is parsed and the PDF is generated by JavaScript running in your own browser. Nothing is transmitted, which makes this safe for drafts, contracts, and internal documentation.",
  },
  {
    question: "Does the converter work offline?",
    answer:
      "Yes. Once this page has loaded you can disconnect and keep converting — no part of the process needs a network connection.",
  },
  {
    question: "What page size and margins does the PDF use?",
    answer:
      "A4 with balanced margins, sized for both on-screen reading and printing. Long documents paginate automatically, and long code blocks and tables continue cleanly onto the next page.",
  },
  {
    question: "Why does my Markdown render differently elsewhere?",
    answer:
      "Markdown has several dialects. This converter follows CommonMark with the GitHub Flavored Markdown extensions most people use: tables, strikethrough, and fenced code. Task lists render as plain bullets, and tool-specific extras like footnotes or LaTeX math are not supported.",
  },
];

// Rendered as a support table below. Written from what the converter genuinely
// does — an honest "no" column is worth more than a wall of green checks.
const supportRows: { feature: string; supported: string }[] = [
  { feature: "Headings (H1–H6)", supported: "Yes — mapped to PDF heading sizes" },
  { feature: "Bold, italic, strikethrough", supported: "Yes" },
  { feature: "Ordered, unordered and nested lists", supported: "Yes, including nesting" },
  { feature: "Links", supported: "Yes — clickable in the PDF" },
  { feature: "Inline code and fenced code blocks", supported: "Yes, monospaced with background" },
  { feature: "Tables (GFM)", supported: "Yes" },
  { feature: "Blockquotes and horizontal rules", supported: "Yes" },
  { feature: "Task lists", supported: "As plain bullets — checkbox state not shown" },
  { feature: "Images", supported: "Not embedded — text content only" },
  { feature: "LaTeX math, footnotes, diagrams", supported: "No — outside GFM" },
];

const steps = [
  {
    name: "Paste or open your Markdown",
    text: "Type directly into the editor, paste from your notes app, or open an existing .md file from your device. The live preview updates as you write.",
  },
  {
    name: "Check the preview",
    text: "The preview shows exactly how headings, lists, tables, and code blocks will be laid out. Fix anything that looks off before exporting.",
  },
  {
    name: "Download the PDF",
    text: "Click Download PDF. The document is generated in your browser as vector text — selectable, searchable, and free of watermarks.",
  },
];

export default function MarkdownToPdfPage() {
  const clusterPosts = getPostsByTopic("markdown to pdf export resume readme syntax cheat sheet");

  return (
    <>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          itemListElement: [
            { "@type": "ListItem", position: 1, name: "Home", item: SITE.url },
            {
              "@type": "ListItem",
              position: 2,
              name: "Markdown to PDF",
              item: `${SITE.url}/markdown-to-pdf`,
            },
          ],
        }}
      />
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "Markdown to PDF Converter",
          url: `${SITE.url}/markdown-to-pdf`,
          applicationCategory: "UtilitiesApplication",
          operatingSystem: "Any",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          featureList:
            "Markdown editor with live preview, vector PDF output, tables, code blocks, A4 layout",
        }}
      />

      <div className="relative overflow-hidden">
        <div className="bg-grid absolute inset-0" aria-hidden />
        <div
          className="absolute left-1/2 top-0 -z-10 h-96 w-[50rem] -translate-x-1/2 rounded-full bg-gradient-to-tr from-indigo-200/50 via-violet-200/30 to-transparent blur-3xl"
          aria-hidden
        />
        <div className="relative mx-auto max-w-6xl px-4 pb-14 pt-12">
          <h1 className="text-center text-3xl font-bold tracking-tight text-neutral-900 sm:text-5xl">
            Markdown to PDF{" "}
            <span className="bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent">
              Converter
            </span>
          </h1>
          <p className="mx-auto mt-4 max-w-2xl text-center text-lg text-neutral-600">
            Write or paste Markdown, preview it live, and download a clean A4 PDF with real
            selectable text. Free, no watermark, and fully private.
          </p>
          <div className="mt-10">
            <MarkdownToPdfTool />
          </div>
        </div>
      </div>

      <section className="mx-auto max-w-3xl px-4 py-12">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
          Why convert Markdown to PDF?
        </h2>
        <div className="prose prose-neutral mt-4 max-w-none">
          <p>
            Markdown is the writing format of choice for developers, technical writers, and
            note-takers — but it is not what you hand to a client, attach to an email, or print.
            PDF is the universal exchange format: it looks identical everywhere and nobody needs
            special software to open it. Converting Markdown to PDF is the natural last step for:
          </p>
          <ul>
            <li>
              <strong>Reports and proposals</strong> written in Markdown that need a professional,
              fixed-layout deliverable.
            </li>
            <li>
              <strong>Documentation and READMEs</strong> shared with people who do not use GitHub.
            </li>
            <li>
              <strong>Notes and study material</strong> from apps like Obsidian or Logseq that you
              want to print or archive.
            </li>
            <li>
              <strong>Resumes and letters</strong> kept in version control as plain text.
            </li>
          </ul>
          <p>
            This converter parses your Markdown and lays it out as a genuine vector PDF — headings,
            tables, code blocks and links included — so the text stays selectable and searchable.
            Curious about other approaches like Pandoc or VS Code extensions? See our guide on{" "}
            <Link href="/blog/convert-markdown-to-pdf">
              every way to convert Markdown to PDF
            </Link>
            , or learn the syntax first with our{" "}
            <Link href="/blog/what-is-markdown-complete-guide">complete Markdown guide</Link>.
          </p>
        </div>
      </section>

      <section className="border-t border-neutral-100 bg-neutral-50/60">
        <div className="mx-auto max-w-6xl px-4 py-16">
          <h2 className="text-center text-3xl font-bold tracking-tight text-neutral-900">
            How to convert Markdown to PDF
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-center text-lg text-neutral-600">
            Three steps, no installation, no account. It takes about ten seconds.
          </p>
          <ol className="mt-12 grid gap-8 sm:grid-cols-3">
            {steps.map((s, i) => (
              <li key={s.name} className="relative rounded-2xl bg-white p-7 shadow-sm ring-1 ring-neutral-100">
                <span className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-indigo-600 to-violet-600 font-bold text-white shadow-md shadow-indigo-500/25">
                  {i + 1}
                </span>
                <h3 className="mt-4 text-lg font-semibold text-neutral-900">{s.name}</h3>
                <p className="mt-2 leading-relaxed text-neutral-600">{s.text}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-14">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
          Real text, not a screenshot
        </h2>
        <div className="prose prose-neutral mt-4 max-w-none prose-a:text-indigo-600">
          <p>
            Plenty of free MD to PDF tools work by rendering your Markdown as a web page and then
            photographing it. The result looks fine until you try to use it: you cannot select a
            sentence, <code>Ctrl+F</code> finds nothing, a screen reader sees an empty page, and the
            file is several megabytes because every page is an image.
          </p>
          <p>
            This converter builds the PDF from the text itself. Your Markdown is parsed into a
            document tree, and each heading, paragraph, list item, and table cell is written into
            the PDF as vector text with its own font and position. That means the output is
            selectable, searchable, copy-pasteable, accessible, and typically a few dozen kilobytes
            rather than a few megabytes — and if you ever need the content back as plain text, a
            round trip through the{" "}
            <Link href="/">PDF to Markdown converter</Link> returns something usable instead of
            requiring <Link href="/blog/extract-text-from-scanned-pdf">OCR on an image</Link>.
          </p>
        </div>
      </section>

      <section className="border-t border-neutral-100 bg-neutral-50/60">
        <div className="mx-auto max-w-4xl px-4 py-14">
          <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
            What Markdown syntax is supported
          </h2>
          <p className="mt-3 text-neutral-600">
            CommonMark plus the GitHub Flavored Markdown extensions most people actually write.
            Where something is not supported, it says so.
          </p>
          <div className="mt-8 overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-neutral-200 bg-neutral-50">
                  <th scope="col" className="px-5 py-4 font-semibold text-neutral-900">Syntax</th>
                  <th scope="col" className="px-5 py-4 font-semibold text-neutral-900">In the PDF</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-100">
                {supportRows.map((row) => (
                  <tr key={row.feature}>
                    <th scope="row" className="px-5 py-4 font-medium text-neutral-700">{row.feature}</th>
                    <td className="px-5 py-4 text-neutral-600">{row.supported}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-sm text-neutral-500">
            Not sure which syntax you need? The{" "}
            <Link href="/blog/markdown-cheat-sheet" className="text-indigo-600 hover:underline">
              Markdown cheat sheet
            </Link>{" "}
            lists every element on one page, and{" "}
            <Link href="/blog/markdown-frontmatter-guide" className="text-indigo-600 hover:underline">
              frontmatter
            </Link>{" "}
            explains the YAML block some editors add at the top of a file.
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-14">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
          Common uses for a Markdown to PDF export
        </h2>
        <div className="prose prose-neutral mt-4 max-w-none prose-a:text-indigo-600">
          <ul>
            <li>
              <strong>A resume kept in version control.</strong> Write it once in Markdown, export a
              clean PDF for every application — see{" "}
              <Link href="/blog/markdown-resume-to-pdf">Markdown resume to PDF</Link>.
            </li>
            <li>
              <strong>A README for people who do not use GitHub.</strong> Clients and managers get a
              document they can open;{" "}
              <Link href="/blog/convert-github-readme-to-pdf">the README guide</Link> covers the
              details, including what happens to badges and relative links.
            </li>
            <li>
              <strong>Notes and study material</strong> from Obsidian, Logseq, or a plain folder of
              files, turned into something printable.
            </li>
            <li>
              <strong>Technical documentation snapshots</strong> — a dated, fixed copy of a spec or
              runbook that will not drift while it is being reviewed.
            </li>
            <li>
              <strong>Reports and proposals</strong> drafted in Markdown for speed, delivered as PDF
              because that is what the recipient expects.
            </li>
          </ul>
          <p>
            The pattern underneath all of these is the same one described in{" "}
            <Link href="/blog/pdf-vs-word-vs-markdown">PDF vs Word vs Markdown</Link>: author in a
            format that is easy to change, export to PDF at the moment a version becomes final.
          </p>
        </div>
      </section>

      <section className="border-t border-neutral-100 bg-neutral-50">
        <div className="mx-auto max-w-6xl px-4 py-14">
          <Faq items={faqItems} />
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-12 text-center">
        <h2 className="text-xl font-bold text-neutral-900">Need the other direction?</h2>
        <p className="mt-2 text-neutral-600">
          Extract clean Markdown from any PDF with our{" "}
          <Link href="/" className="font-medium text-indigo-600 hover:underline">
            PDF to Markdown converter
          </Link>
          .
        </p>
      </section>

      <BlogCluster posts={clusterPosts} heading="Learn more about Markdown & PDF" />
    </>
  );
}
