import type { Metadata } from "next";
import Link from "next/link";
import MarkdownToPdfTool from "@/components/MarkdownToPdfTool";
import Faq from "@/components/Faq";
import AdSlot from "@/components/AdSlot";
import { Breadcrumbs, RelatedTools, ToolGuides, ToolJsonLd, toolCrumbs } from "@/components/ToolSeo";
import { getTool } from "@/lib/tools";

// Measured 2026-09-17 via the GSC URL Inspection API: this page was still
// "Discovered - currently not indexed" and had never been crawled, three months
// after launch — while carrying only 672 words, the thinnest page on the site,
// and zero editorial inbound links (header, footer and the blog aside link here
// on every page, but no in-content link ever did). Both were fixed together:
// the page was rebuilt below, and four contextual links were added from
// convert-markdown-to-pdf, markdown-resume-to-pdf, convert-github-readme-to-pdf
// and markdown-cheat-sheet.
// 2026-09-18: the title now names Mermaid and math. Google's autocomplete for
// "markdown to pdf with …" suggests mermaid, latex, images, math and css — and
// every competing converter supports them. This page did not until today.
const DESCRIPTION =
  "Free Markdown to PDF converter with Mermaid diagrams, LaTeX math, images and syntax highlighting. Real selectable text, any language, nothing uploaded.";

export const metadata: Metadata = {
  // 2026-09-26 (DataForSEO, US): "md to pdf" has the same volume as "markdown to
  // pdf" (14,800/mo each, KD 17 vs 26) and "convert md to pdf" another 3,600; the
  // title named neither. Mermaid & math stay: they are what sets the tool apart.
  title: "Markdown to PDF (MD to PDF) — Mermaid & Math",
  description: DESCRIPTION,
  alternates: { canonical: "/md-to-pdf" },
  openGraph: {
    title: "Markdown to PDF Converter — Mermaid, LaTeX math, images",
    description:
      "Convert Markdown to PDF for free, with diagrams, formulas and images. Real selectable text, no watermark, nothing uploaded.",
    url: "/md-to-pdf",
  },
};

const faqItems = [
  {
    question: "How do I convert Markdown to PDF?",
    answer:
      "Paste or type your Markdown in the editor above, or open an existing .md file. Check the live preview, then click Download PDF — the document is generated instantly in your browser.",
  },
  {
    question: "What Markdown features are supported?",
    answer:
      "Everything in CommonMark and GitHub Flavored Markdown: headings, emphasis, strikethrough, nested and task lists, links, images, fenced code with syntax highlighting, blockquotes, tables with alignment, and horizontal rules — plus Mermaid diagrams and LaTeX math. The table below lists exactly what each export does.",
  },
  {
    question: "Is the PDF real text or an image?",
    answer:
      "Real text. The PDF is generated as vector text, so it is selectable, searchable, accessible to screen readers, and small in file size — unlike converters that screenshot the page.",
  },
  {
    question: "Does the converter add a watermark?",
    answer: "No. The generated PDF is completely clean, with no watermark or branding.",
  },
  {
    question: "Can I use it for GitHub README files?",
    answer:
      "Yes. Open your README.md in the editor and download it as a PDF — useful for sharing documentation with people outside your repository.",
  },
  {
    question: "How do I convert an .md file to PDF?",
    answer:
      "Open the file on your computer, copy its contents into the editor above (or use the file picker), check the preview, and click Download PDF. There is nothing to install and no account to create — MD to PDF conversion happens entirely in this page.",
  },
  {
    question: "Are my files uploaded to a server?",
    answer:
      "No. The Markdown is parsed and the PDF is generated by JavaScript running in your own browser. Nothing is transmitted, which makes this safe for drafts, contracts, and internal documentation. Local images you attach stay on your device too.",
  },
  {
    question: "Does the converter need an internet connection?",
    answer:
      "Only to load the page and the converter. Your Markdown is never transmitted — the PDF is generated on your device, so nothing you write leaves your browser.",
  },
  {
    question: "What page size and margins does the PDF use?",
    answer:
      "A4 with balanced margins, sized for both on-screen reading and printing. Long documents paginate automatically, and long code blocks and tables continue cleanly onto the next page.",
  },
  {
    question: "Why does my Markdown render differently elsewhere?",
    answer:
      "Markdown has several dialects. This converter follows CommonMark with the GitHub Flavored Markdown extensions most people use (tables, strikethrough, task lists, fenced code), plus Mermaid and $…$ / $$…$$ math. Footnotes, definition lists and raw HTML are not rendered.",
  },
  {
    question: "Can I include Mermaid diagrams?",
    answer:
      "Yes. Put the diagram in a fenced code block tagged mermaid (```mermaid). Flowcharts, sequence, class, state, Gantt, pie and ER diagrams all work. Save as PDF keeps them as sharp vector graphics; Download PDF embeds them as high-resolution images.",
  },
  {
    question: "Does it support LaTeX math?",
    answer:
      "Yes: $E = mc^2$ for inline math and $$ … $$ for a displayed equation, in standard LaTeX syntax (rendered with MathJax, including the AMS packages). A dollar sign followed by a space or a digit is left as text, so prices like $5 are not mistaken for math.",
  },
  {
    question: "How do I add images?",
    answer:
      "Images on the web work as usual with ![description](https://…), as long as their host allows other sites to load them (most do). For images on your computer, click Add images and select them; ![logo](logo.png) then finds the file by name. The files stay in your browser.",
  },
  {
    question: "What is the difference between Download PDF and Save as PDF?",
    answer:
      "Download PDF builds the file directly and instantly, with selectable text, for Latin, Greek and Cyrillic scripts. Save as PDF uses your browser's own print engine: it keeps diagrams and formulas as vector graphics and handles every language — Arabic, Hebrew, Chinese, Japanese, Korean, emoji. Choose “Save as PDF” as the printer in the dialog that opens.",
  },
];

// Rendered as a support table below. Written from what the converter genuinely
// does — an honest "no" column is worth more than a wall of green checks.
const supportRows: { feature: string; supported: string }[] = [
  { feature: "Headings (H1–H6)", supported: "Yes" },
  { feature: "Bold, italic, strikethrough", supported: "Yes" },
  { feature: "Ordered, nested and task lists", supported: "Yes — task lists get real checkboxes" },
  { feature: "Links", supported: "Yes — clickable in the PDF" },
  { feature: "Code blocks", supported: "Yes, with syntax highlighting for 20+ languages" },
  { feature: "Tables (GFM)", supported: "Yes, with column alignment" },
  { feature: "Blockquotes and horizontal rules", supported: "Yes" },
  { feature: "Images", supported: "Yes — web images whose host allows it, and local files you attach" },
  { feature: "Mermaid diagrams", supported: "Yes — vector with Save as PDF, high-resolution image with Download PDF" },
  { feature: "LaTeX math ($…$, $$…$$)", supported: "Yes — vector with Save as PDF, high-resolution image with Download PDF" },
  { feature: "Greek, Cyrillic and other Latin-like scripts", supported: "Yes, in both exports" },
  { feature: "Arabic, Hebrew, Chinese, Japanese, Korean, emoji", supported: "Save as PDF only" },
  { feature: "Footnotes, raw HTML", supported: "No" },
];

const steps = [
  {
    name: "Paste or open your Markdown",
    text: "Type directly into the editor, paste from your notes app, or open an existing .md file from your device. The live preview updates as you write.",
  },
  {
    name: "Check the preview",
    text: "The preview shows exactly how headings, lists, tables, and code blocks will be laid out. Fix anything that looks off before exporting.",
  },
  {
    name: "Download the PDF",
    text: "Click Download PDF for an instant file, or Save as PDF for full fidelity through your browser. Either way: vector text, no watermark.",
  },
];

export default function MarkdownToPdfPage() {
  const tool = getTool("markdown-to-pdf")!;

  return (
    <>
      <ToolJsonLd slug="markdown-to-pdf" description={DESCRIPTION} />
      <div className="relative overflow-hidden">
        <div className="bg-grid absolute inset-0" aria-hidden />
        <div
          className="absolute left-1/2 top-0 -z-10 h-96 w-[50rem] -translate-x-1/2 rounded-full bg-gradient-to-tr from-indigo-200/50 via-violet-200/30 to-transparent blur-3xl"
          aria-hidden
        />
        <div className="relative mx-auto max-w-6xl px-4 pb-14 pt-8">
          <Breadcrumbs crumbs={toolCrumbs(tool)} />
          <h1 className="mt-6 text-center text-3xl font-bold tracking-tight text-neutral-900 sm:text-5xl">
            Markdown to PDF{" "}
            <span className="bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent">
              Converter
            </span>
          </h1>
          <p className="mx-auto mt-4 max-w-2xl text-center text-lg text-neutral-600">
            Write or paste Markdown, preview it live, and download a clean A4 PDF with real
            selectable text — Mermaid diagrams, LaTeX math, images and highlighted code included.
            Free, no watermark, and nothing leaves your browser.
          </p>
          <div className="mt-10">
            <MarkdownToPdfTool />
          </div>
        </div>
      </div>

      <section className="mx-auto max-w-3xl px-4 py-12">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
          Why convert Markdown to PDF?
        </h2>
        <div className="prose prose-neutral mt-4 max-w-none">
          <p>
            Markdown is the writing format of choice for developers, technical writers, and
            note-takers — but it is not what you hand to a client, attach to an email, or print.
            PDF is the universal exchange format: it looks identical everywhere and nobody needs
            special software to open it. Converting Markdown to PDF is the natural last step for:
          </p>
          <ul>
            <li>
              <strong>Reports and proposals</strong> written in Markdown that need a professional,
              fixed-layout deliverable.
            </li>
            <li>
              <strong>Documentation and READMEs</strong> shared with people who do not use GitHub.
            </li>
            <li>
              <strong>Notes and study material</strong> from apps like Obsidian or Logseq that you
              want to print or archive.
            </li>
            <li>
              <strong>Resumes and letters</strong> kept in version control as plain text.
            </li>
          </ul>
          <p>
            This converter parses your Markdown and lays it out as a genuine vector PDF — headings,
            tables, code blocks and links included — so the text stays selectable and searchable.
            Curious about other approaches like Pandoc or VS Code extensions? See our guide on{" "}
            <Link href="/blog/convert-markdown-to-pdf">
              every way to convert Markdown to PDF
            </Link>
            , or learn the syntax first with our{" "}
            <Link href="/blog/what-is-markdown-complete-guide">complete Markdown guide</Link>.
          </p>
        </div>
      </section>

      <section className="border-t border-neutral-100 bg-neutral-50/60">
        <div className="mx-auto max-w-6xl px-4 py-16">
          <h2 className="text-center text-3xl font-bold tracking-tight text-neutral-900">
            How to convert Markdown to PDF
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-center text-lg text-neutral-600">
            Three steps, no installation, no account. It takes about ten seconds.
          </p>
          <ol className="mt-12 grid gap-8 sm:grid-cols-3">
            {steps.map((s, i) => (
              <li key={s.name} className="relative rounded-2xl bg-white p-7 shadow-sm ring-1 ring-neutral-100">
                <span className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-indigo-600 to-violet-600 font-bold text-white shadow-md shadow-indigo-500/25">
                  {i + 1}
                </span>
                <h3 className="mt-4 text-lg font-semibold text-neutral-900">{s.name}</h3>
                <p className="mt-2 leading-relaxed text-neutral-600">{s.text}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <AdSlot placement="tool" />

      <section className="mx-auto max-w-3xl px-4 py-14">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
          Real text, not a screenshot
        </h2>
        <div className="prose prose-neutral mt-4 max-w-none prose-a:text-indigo-600">
          <p>
            Plenty of free MD to PDF tools work by rendering your Markdown as a web page and then
            photographing it. The result looks fine until you try to use it: you cannot select a
            sentence, <code>Ctrl+F</code> finds nothing, a screen reader sees an empty page, and the
            file is several megabytes because every page is an image.
          </p>
          <p>
            This converter builds the PDF from the text itself. Your Markdown is parsed into a
            document tree, and each heading, paragraph, list item, and table cell is written into
            the PDF as vector text with its own font and position. That means the output is
            selectable, searchable, copy-pasteable, accessible, and — for a text document — typically
            a few dozen kilobytes rather than a few megabytes — and if you ever need the content back as plain text, a
            round trip through the{" "}
            <Link href="/">PDF to Markdown converter</Link> returns something usable instead of
            requiring <Link href="/blog/extract-text-from-scanned-pdf">OCR on an image</Link>.
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 pb-14">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
          Mermaid diagrams, LaTeX math and images
        </h2>
        <div className="prose prose-neutral mt-4 max-w-none prose-a:text-indigo-600">
          <p>
            Technical documents rarely stop at text. A fenced code block tagged{" "}
            <code>mermaid</code> becomes a diagram — flowcharts, sequence diagrams, Gantt charts,
            class and state diagrams. Math between dollar signs is typeset with MathJax, so{" "}
            <code>$\frac{"{a}"}{"{b}"}$</code> looks like it does in a paper. Images load from the
            web, or from files you attach with <strong>Add images</strong>, matched by file name.
          </p>
          <p>
            Diagram and formula libraries are heavy, so they are only downloaded when your document
            actually uses them — a plain document never pays for them. Click{" "}
            <strong>Try diagrams &amp; math</strong> above to see an example.
          </p>
          <p>
            <strong>Which export to use?</strong> <em>Download PDF</em> is instant and produces
            selectable text; diagrams and formulas are embedded as high-resolution images.{" "}
            <em>Save as PDF</em> hands the page to your browser&apos;s print engine, which keeps
            them as vector graphics and handles every writing system, including right-to-left
            scripts. Pick the clean or academic style before saving.
          </p>
        </div>
      </section>

      <section className="border-t border-neutral-100 bg-neutral-50/60">
        <div className="mx-auto max-w-4xl px-4 py-14">
          <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
            What Markdown syntax is supported
          </h2>
          <p className="mt-3 text-neutral-600">
            CommonMark plus the GitHub Flavored Markdown extensions most people actually write.
            Where something is not supported, it says so.
          </p>
          <div className="mt-8 overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-neutral-200 bg-neutral-50">
                  <th scope="col" className="px-5 py-4 font-semibold text-neutral-900">Syntax</th>
                  <th scope="col" className="px-5 py-4 font-semibold text-neutral-900">In the PDF</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-100">
                {supportRows.map((row) => (
                  <tr key={row.feature}>
                    <th scope="row" className="px-5 py-4 font-medium text-neutral-700">{row.feature}</th>
                    <td className="px-5 py-4 text-neutral-600">{row.supported}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-sm text-neutral-500">
            Not sure which syntax you need? The{" "}
            <Link href="/blog/markdown-cheat-sheet" className="text-indigo-600 hover:underline">
              Markdown cheat sheet
            </Link>{" "}
            lists every element on one page, and{" "}
            <Link href="/blog/markdown-frontmatter-guide" className="text-indigo-600 hover:underline">
              frontmatter
            </Link>{" "}
            explains the YAML block some editors add at the top of a file.
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-14">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900">
          Common uses for a Markdown to PDF export
        </h2>
        <div className="prose prose-neutral mt-4 max-w-none prose-a:text-indigo-600">
          <ul>
            <li>
              <strong>A resume kept in version control.</strong> Write it once in Markdown, export a
              clean PDF for every application — see{" "}
              <Link href="/blog/markdown-resume-to-pdf">Markdown resume to PDF</Link>.
            </li>
            <li>
              <strong>A README for people who do not use GitHub.</strong> Clients and managers get a
              document they can open;{" "}
              <Link href="/blog/convert-github-readme-to-pdf">the README guide</Link> covers the
              details, including what happens to badges and relative links.
            </li>
            <li>
              <strong>Notes and study material</strong> from Obsidian, Logseq, or a plain folder of
              files, turned into something printable.
            </li>
            <li>
              <strong>Technical documentation snapshots</strong> — a dated, fixed copy of a spec or
              runbook that will not drift while it is being reviewed.
            </li>
            <li>
              <strong>Reports and proposals</strong> drafted in Markdown for speed, delivered as PDF
              because that is what the recipient expects.
            </li>
          </ul>
          <p>
            The pattern underneath all of these is the same one described in{" "}
            <Link href="/blog/pdf-vs-word-vs-markdown">PDF vs Word vs Markdown</Link>: author in a
            format that is easy to change, export to PDF at the moment a version becomes final.
          </p>
        </div>
      </section>

      <AdSlot placement="tool" />

      <section className="border-t border-neutral-100 bg-neutral-50">
        <div className="mx-auto max-w-6xl px-4 py-14">
          <Faq items={faqItems} />
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-12 text-center">
        <h2 className="text-xl font-bold text-neutral-900">Need the other direction?</h2>
        <p className="mt-2 text-neutral-600">
          Extract clean Markdown from any PDF with our{" "}
          <Link href="/" className="font-medium text-indigo-600 hover:underline">
            PDF to Markdown converter
          </Link>
          .
        </p>
      </section>

      <RelatedTools slug="markdown-to-pdf" />
      <ToolGuides slug="markdown-to-pdf" heading="Guides on Markdown & PDF" />
    </>
  );
}
